MAuthentication/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path, re_path

from . import views

app_name = 'Account'

urlpatterns = [
    
    re_path(r"^accounts/register/$", views.RegistrationView.as_view(), name="register-view"),
    re_path(r"^accounts/login/$", views.LoginView.as_view(), name="login-view"),
    re_path(r"^accounts/logout/$", views.logoutview, name="logout-view"),
    path("activate/<uidb64>/<token>/", views.ActivateAccountView.as_view(), name="account-activation-view"),
    path("set-new-password/<uidb64>/<token>/", views.SetNewPasswordView.as_view(), name="set-new-password-view"),
    re_path(r"^request-reset-email/$", views.RequestResetEmailView.as_view(), name="request-reset-email-view"),
]

MChat/urls.py
from django.urls import path
from . import views
app_name = 'MChat'
urlpatterns = [
    path('chat/', views.messages_page, name='chat-view'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <link rel="icon" type="image/x-icon" href="{% static 'images/favicon.ico' %}">
  <link rel="stylesheet" href="https://unicons.iconscout.com/release/v4.0.0/css/line.css" />

  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
  integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
  <script src="https://kit.fontawesome.com/d3d6f2df1f.js" crossorigin="anonymous"></script>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.2/font/bootstrap-icons.css">

  <link rel="stylesheet"
    href="https://cdnjs.cloudflare.com/ajax/libs/magnific-popup.js/1.1.0/magnific-popup.min.css" />
  <link rel="stylesheet" href="{% static 'css/authenticationstyle.css' %}">
  <link rel="stylesheet" href="{% static 'css/frontendbase.css' %}">
  <link rel="stylesheet" href="{% static 'css/UserProfile.css' %}">

<title>
  Instagram
  {% block title %}
  
  {% endblock %}
</title>
<!-- 
  <link rel="stylesheet" href="{% static 'css/style.css' %}" /> -->

</head>

<body>
      <!--Navbar-->
      <nav class="navbar fixed-top  navbar-expand-lg navbar-light bg-light">
        <div class="container justify-content-center">

            <div class="d-flex flex-row justify-content-between align-items-center col-9">
                <!--Brand-->
                <a class="navbar-brand" href="/">
                    <img src="{% static 'images/ig-logo1.png' %}" alt="img1" href="/" loading="lazy">
                </a>

                <!--Search Form-->
                <div class="search-engine">
                    <form id="search-form"  class="form-inline my-2 my-lg-0">
                        {% csrf_token %}
                        <input id="search-input" name="query" class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
                    </form>
                </div>
                <!--Search Query-->
                <div class="search-query invisible justify-content-center align-items-center" id="search-query">
                    <div class="spinner-border" role="status">
                        <span class="visually-hidden">Loading...</span>
                      </div>
                </div>

                <div class="d-flex flex-row">
                    <ul class="list-inline m-0">

                        <li class="list-inline-item">
                            <a href="#" class="link-menu">
                                <svg width="1.5em" height="1.5em" viewBox="0 0 16 16" class="bi bi-house-door-fill"
                                    fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                                    <path
                                        d="M6.5 10.995V14.5a.5.5 0 0 1-.5.5H2a.5.5 0 0 1-.5-.5v-7a.5.5 0 0 1 .146-.354l6-6a.5.5 0 0 1 .708 0l6 6a.5.5 0 0 1 .146.354v7a.5.5 0 0 1-.5.5h-4a.5.5 0 0 1-.5-.5V11c0-.25-.25-.5-.5-.5H7c-.25 0-.5.25-.5.495z" />
                                    <path fill-rule="evenodd"
                                        d="M13 2.5V6l-2-2V2.5a.5.5 0 0 1 .5-.5h1a.5.5 0 0 1 .5.5z" />
                                </svg>
                            </a>
                        </li>

                        <li class="list-inline-item ml-2">
                            <a href="{% url 'MChat:chat-view' %}" class="link-menu">
                                <svg aria-label="Messenger" class="_8-yf5 " color="#262626" fill="#262626" height="24"
                                    role="img" viewBox="0 0 24 24" width="24">
                                    <path
                                        d="M12.003 2.001a9.705 9.705 0 110 19.4 10.876 10.876 0 01-2.895-.384.798.798 0 00-.533.04l-1.984.876a.801.801 0 01-1.123-.708l-.054-1.78a.806.806 0 00-.27-.569 9.49 9.49 0 01-3.14-7.175 9.65 9.65 0 0110-9.7z"
                                        fill="none" stroke="currentColor" stroke-miterlimit="10" stroke-width="1.739">
                                    </path>
                                    <path
                                        d="M17.79 10.132a.659.659 0 00-.962-.873l-2.556 2.05a.63.63 0 01-.758.002L11.06 9.47a1.576 1.576 0 00-2.277.42l-2.567 3.98a.659.659 0 00.961.875l2.556-2.049a.63.63 0 01.759-.002l2.452 1.84a1.576 1.576 0 002.278-.42z"
                                        fill-rule="evenodd"></path>
                                </svg>
                            </a>

                        </li>

                        <!--Icons-->
                        <li class="list-inline-item ml-2  ">
                            <a href="#test-form" class="popup-with-form ">
                                <svg aria-label="New Post" class="_8-yf5 " color="#262626" fill="#262626" height="24"
                                    role="img" viewBox="0 0 24 24" width="24">
                                    <path
                                        d="M2 12v3.45c0 2.849.698 4.005 1.606 4.944.94.909 2.098 1.608 4.946 1.608h6.896c2.848 0 4.006-.7 4.946-1.608C21.302 19.455 22 18.3 22 15.45V8.552c0-2.849-.698-4.006-1.606-4.945C19.454 2.7 18.296 2 15.448 2H8.552c-2.848 0-4.006.699-4.946 1.607C2.698 4.547 2 5.703 2 8.552z"
                                        fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round"
                                        stroke-width="2"></path>
                                    <line fill="none" stroke="currentColor" stroke-linecap="round"
                                        stroke-linejoin="round" stroke-width="2" x1="6.545" x2="17.455" y1="12.001"
                                        y2="12.001"></line>
                                    <line fill="none" stroke="currentColor" stroke-linecap="round"
                                        stroke-linejoin="round" stroke-width="2" x1="12.003" x2="12.003" y1="6.545"
                                        y2="17.455"></line>
                                </svg>
                            </a>

                            <form id="test-form" class="border-2 mfp-hide white-popup-wide">
                                <p style="font-size:1.4rem;">Create New Post</p>
                                <hr>
                                <fieldset style="border:0;">

                                    <svg aria-label="Icon to represent media such as images or videos" class="_8-yf5 "
                                        color="#262626" fill="#262626" height="77" role="img" viewBox="0 0 97.6 77.3"
                                        width="96">
                                        <path
                                            d="M16.3 24h.3c2.8-.2 4.9-2.6 4.8-5.4-.2-2.8-2.6-4.9-5.4-4.8s-4.9 2.6-4.8 5.4c.1 2.7 2.4 4.8 5.1 4.8zm-2.4-7.2c.5-.6 1.3-1 2.1-1h.2c1.7 0 3.1 1.4 3.1 3.1 0 1.7-1.4 3.1-3.1 3.1-1.7 0-3.1-1.4-3.1-3.1 0-.8.3-1.5.8-2.1z"
                                            fill="currentColor"></path>
                                        <path
                                            d="M84.7 18.4L58 16.9l-.2-3c-.3-5.7-5.2-10.1-11-9.8L12.9 6c-5.7.3-10.1 5.3-9.8 11L5 51v.8c.7 5.2 5.1 9.1 10.3 9.1h.6l21.7-1.2v.6c-.3 5.7 4 10.7 9.8 11l34 2h.6c5.5 0 10.1-4.3 10.4-9.8l2-34c.4-5.8-4-10.7-9.7-11.1zM7.2 10.8C8.7 9.1 10.8 8.1 13 8l34-1.9c4.6-.3 8.6 3.3 8.9 7.9l.2 2.8-5.3-.3c-5.7-.3-10.7 4-11 9.8l-.6 9.5-9.5 10.7c-.2.3-.6.4-1 .5-.4 0-.7-.1-1-.4l-7.8-7c-1.4-1.3-3.5-1.1-4.8.3L7 49 5.2 17c-.2-2.3.6-4.5 2-6.2zm8.7 48c-4.3.2-8.1-2.8-8.8-7.1l9.4-10.5c.2-.3.6-.4 1-.5.4 0 .7.1 1 .4l7.8 7c.7.6 1.6.9 2.5.9.9 0 1.7-.5 2.3-1.1l7.8-8.8-1.1 18.6-21.9 1.1zm76.5-29.5l-2 34c-.3 4.6-4.3 8.2-8.9 7.9l-34-2c-4.6-.3-8.2-4.3-7.9-8.9l2-34c.3-4.4 3.9-7.9 8.4-7.9h.5l34 2c4.7.3 8.2 4.3 7.9 8.9z"
                                            fill="currentColor"></path>
                                        <path
                                            d="M78.2 41.6L61.3 30.5c-2.1-1.4-4.9-.8-6.2 1.3-.4.7-.7 1.4-.7 2.2l-1.2 20.1c-.1 2.5 1.7 4.6 4.2 4.8h.3c.7 0 1.4-.2 2-.5l18-9c2.2-1.1 3.1-3.8 2-6-.4-.7-.9-1.3-1.5-1.8zm-1.4 6l-18 9c-.4.2-.8.3-1.3.3-.4 0-.9-.2-1.2-.4-.7-.5-1.2-1.3-1.1-2.2l1.2-20.1c.1-.9.6-1.7 1.4-2.1.8-.4 1.7-.3 2.5.1L77 43.3c1.2.8 1.5 2.3.7 3.4-.2.4-.5.7-.9.9z"
                                            fill="currentColor"></path>
                                    </svg>
                                    <p style="font-size: 1rem;">Drag photos and videos here.</p>
                                    caption and location, comment disable
                                </fieldset>

                                <input type='file' id="getFile">

                            </form>

                        </li>

                        <li class="list-inline-item ml-2">
                            <a href="#" class="link-menu">
                                <svg width="1.5em" height="1.5em" viewBox="0 0 16 16" class="bi bi-compass"
                                    fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                                    <path fill-rule="evenodd"
                                        d="M8 15.016a6.5 6.5 0 1 0 0-13 6.5 6.5 0 0 0 0 13zm0 1a7.5 7.5 0 1 0 0-15 7.5 7.5 0 0 0 0 15z" />
                                    <path
                                        d="M6 1a1 1 0 0 1 1-1h2a1 1 0 0 1 0 2H7a1 1 0 0 1-1-1zm.94 6.44l4.95-2.83-2.83 4.95-4.95 2.83 2.83-4.95z" />
                                </svg>
                            </a>
                        </li>

                        <li class="list-inline-item ml-2">
                            <a href="#" class="link-menu">
                                <svg width="1.5em" height="1.5em" viewBox="0 0 16 16" class="bi bi-heart"
                                    fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                                    <path fill-rule="evenodd"
                                        d="M8 2.748l-.717-.737C5.6.281 2.514.878 1.4 3.053c-.523 1.023-.641 2.5.314 4.385.92 1.815 2.834 3.989 6.286 6.357 3.452-2.368 5.365-4.542 6.286-6.357.955-1.886.838-3.362.314-4.385C13.486.878 10.4.28 8.717 2.01L8 2.748zM8 15C-7.333 4.868 3.279-3.04 7.824 1.143c.06.055.119.112.176.171a3.12 3.12 0 0 1 .176-.17C12.72-3.042 23.333 4.867 8 15z" />
                                </svg>
                            </a>
                        </li>

                        <li class="list-inline-item ml-2 dropdown text-end align-middle">

                            <a href="#" class="d-block link-dark text-decoration-none dropdown-toggle"
                                id="dropdownUser1" data-bs-toggle="dropdown" aria-expanded="false">
                                <img src="{{request.user.image.url}}" alt="mdo" width="29" height="29"
                                    class="rounded-circle">
                            </a>
                            <ul class="dropdown-menu text-small" aria-labelledby="dropdownUser1">
                                <li><a class="dropdown-item p-0" href="#"><i
                                            class="bi bi-person-circle mx-3"></i>Profile</a></li>
                                <li class="mt-2"><a class="dropdown-item p-0" href="#"><i
                                            class="bi bi-bookmark mx-3"></i>Saved</a></li>
                                <li class="mt-2"><a class="dropdown-item p-0" href="#"><i
                                            class="bi bi-gear-wide mx-3"></i>Settings</a></li>

                                <hr>
                                <li><a class="dropdown-item" href="{% url 'Account:logout-view' %}">Log out</a></li>
                            </ul>

                        </li>

                    </ul>
                </div>
            </div>
        </div>
    </nav>
  {% block body %} {% endblock %}
</body>

<footer>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/magnific-popup.js/1.1.0/jquery.magnific-popup.min.js"></script>

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
      crossorigin="anonymous"></script>
  <script src="{% static 'js/main.js' %}"></script>
  <script src="https://www.google.com/recaptcha/api.js"></script>
  {% include 'utilities/flash_message.html' %}

  <script src="{% static 'js/frontendbase.js' %}""></script>
</footer>


</html>